In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [3]:
# creating weekly sales 
weekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almon Butter", "Peanut Butter", "Chasew Butter"])
weekly_sales

Almon Butter  Peanut Butter  Chasew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thurs             4              6             12
Fri               1              6              7

In [4]:
# creating prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [5]:
# create butter_prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                              index=["Price"],
                              columns=["Almon Butter", "Peanut Butter", "Chasew Butter"])
butter_prices

Almon Butter  Peanut Butter  Chasew Butter
Price            10              8             12

In [6]:
# total price

In [7]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [8]:
sales_amount.shape

(5, 3)

In [9]:
sales_amount.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]], dtype=int32)

In [10]:
prices

array([10,  8, 12])

In [11]:
prices.shape

(3,)

In [12]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [13]:
# daily sale
butter_prices

Almon Butter  Peanut Butter  Chasew Butter
Price            10              8             12

In [14]:
weekly_sales

Almon Butter  Peanut Butter  Chasew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thurs             4              6             12
Fri               1              6              7

In [15]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [16]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [17]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almon Butter  Peanut Butter  Chasew Butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thurs             4              6             12        232
Fri               1              6              7        142