Numpy

In [1]:
# 1. Numerical Python
# 2. Fundamental package form numerical and scientific computation
# 3. provides multi-dim array object
# 4. type -> ndarray <- object
# 5. consists of homogeneous elements
# 6. written in c(high performance and memory efficient), cython and python
# 7. created by Travis Oliphant in 2005
# 8. faster than list
# 9. fixed size at creation
# 10. changing size of an array will create an new array and delete the original
# 11. provides tools for mathematical, statistical, logical and linear algebra operations efficiently

In [2]:
import numpy as np

In [3]:
arr0 = np.array(0)  # 0-d (scalar)
print(arr0)
print("dim =", arr0.ndim)
print("shape =", arr0.shape)
print("size =", arr0.size)

0
dim = 0
shape = ()
size = 1


In [4]:
arr1 = np.array([0, 1, 2, 3, 4, 5])  #1-d (vector)
print(arr1)
print("dim =", arr1.ndim)
print("shape =", arr1.shape)
print("size =", arr1.size)

[0 1 2 3 4 5]
dim = 1
shape = (6,)
size = 6


In [5]:
arr2 = np.array([[0, 1, 2, 3,],  #2-d (matrix)
                  [4, 5, 6, 7]
                ])
print(arr2)
print("dim =", arr2.ndim)
print("shape =", arr2.shape)
print("size =", arr2.size)

[[0 1 2 3]
 [4 5 6 7]]
dim = 2
shape = (2, 4)
size = 8


In [6]:
arr3 = np.array([[[0,1,2,3], [4,5,6,7]],[[8,9,10,11], [13,14,15,16]]])  #3-d (tensor)
print(arr3)
print("dim =", arr3.ndim)
print("shape =", arr3.shape)
print("datatype =", arr3.dtype)
print("size =", arr3.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [13 14 15 16]]]
dim = 3
shape = (2, 2, 4)
datatype = int64
size = 16


In [7]:
n_arr1 = np.array(["1","2","3"], dtype='i')
print(n_arr1)

[1 2 3]


In [8]:
n_arr2 = np.array(n_arr1, dtype=bool)
print(n_arr2)

[ True  True  True]


In [9]:
# astype
# change in existing array

In [10]:
n_arr3 = np.array([[1,2,3],[4,5,6]]).astype(bool)
print(n_arr3)

[[ True  True  True]
 [ True  True  True]]


In [11]:
print(arr3)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [13 14 15 16]]]


In [12]:
# arang and reshape

In [13]:
n_arr3 = np.arange(0, 20).reshape(5,4)
print(n_arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
# flatten -> multi-dim to 1-d

In [15]:
n_arr4 = np.arange(20, 50, 2).reshape(3,5)
print(n_arr4)

[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [16]:
n_arr5 = n_arr4.reshape(-1)
print(n_arr5)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [17]:
np.ones((2,3), dtype = 'i')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [18]:
np.zeros((2,3), dtype = 'i')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [19]:
np.linspace(0, 20, num = 20, dtype = 'i').reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 20]], dtype=int32)

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# scalar operations

In [22]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
n_a = a*2
print(n_a)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [24]:
n_a1 = a+2
print(n_a1)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [25]:
# copy(doesn't reflect changes in original array) and view(reflect changes in original array)

In [26]:
arr = np.arange(0,15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
a = arr.copy()
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
a[0,1] = 10
print(a)

[[ 0 10  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
b = arr.view()
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [31]:
b[0,0] = 25
print(b)

[[25  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [32]:
print(arr)

[[25  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [33]:
np.shares_memory(arr, a)

False

In [34]:
np.shares_memory(arr, b)

True

In [35]:
# iteration

In [36]:
arr = np.arange(0,15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [37]:
for i in arr:  # simple loop
    for y in i:
        print(y, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [38]:
for i in np.nditer(arr):
    print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [39]:
for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14


In [40]:
# vector operation -> performed b/w same shape of arrays

In [41]:
a = np.array([[0,1,2], [3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [42]:
b = np.array([[6,7,8], [9,10,11]])
print(b)

[[ 6  7  8]
 [ 9 10 11]]


In [43]:
add = a+b
print(add)

[[ 6  8 10]
 [12 14 16]]


In [44]:
mul = a*b
print(mul)

[[ 0  7 16]
 [27 40 55]]


In [45]:
# indexing and slicing 

In [46]:
arr = np.arange(0,12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
print(arr[1,1])

5


In [48]:
print(arr[0, :])

[0 1 2 3]


In [49]:
print(arr[:, 2])

[ 2  6 10]


In [50]:
print(arr[1:, 1:3])

[[ 5  6]
 [ 9 10]]


In [51]:
print(arr[::2, 0::3])

[[ 0  3]
 [ 8 11]]


In [52]:
print(arr[::2, 1::2])

[[ 1  3]
 [ 9 11]]


In [53]:
# transpose

In [54]:
np.transpose(arr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
# numpy some fn

In [57]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.max(arr, axis = 0)

array([7, 8, 9])

In [59]:
np.max(arr, axis = 1)

array([3, 6, 9])

In [60]:
# stacking

In [61]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [62]:
np.stack((a,b), axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
np.stack((a,b), axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [64]:
# hstack and vstack

In [65]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
# concatenation -> same hstack and vstack but you need to control axis here

In [68]:
new_a = np.concatenate((a,b), axis = 0)
print(new_a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [69]:
new_b = np.concatenate((a,b), axis = 1)
print(new_b)

[[1 2 5 6]
 [3 4 7 8]]


In [70]:
# splitting

In [71]:
np.hsplit(new_b, 2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [72]:
np.hsplit(new_b, 4)

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[5],
        [7]]),
 array([[6],
        [8]])]

In [73]:
np.vsplit(new_a, 2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [74]:
# array_split() -> can split array in any no.

In [75]:
np.array_split(new_a, 10)

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64)]

In [76]:
# Camparision b/w numy and list

In [77]:
lst1 = [i for i in range(10000000)]
lst2 = [i for i in range(10000000, 20000000)]
new_lst = []

import time 
start = time.time()

for i in range(len(lst1)):
    new_lst.append(lst1[i]+lst2[i])

print(time.time()-start)

1.536255121231079


In [78]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()

c = a+b

print(time.time()-start)

0.045906782150268555


In [79]:
# fancy indexing

In [80]:
a = np.arange(0,12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [81]:
print(a[[0,2,3]])

[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [82]:
print(a[:, [0,2]])

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [83]:
# boolean indexing

In [84]:
a = np.array([10,20,30,40,50])
print(a[a>25])

[30 40 50]


In [85]:
# numpy random fn

In [86]:
np.random.randint(0, 12, (2,2))

array([[11,  4],
       [ 5,  2]], dtype=int32)

In [87]:
np.random.rand(2,4)

array([[0.49936506, 0.6860227 , 0.12845265, 0.53153227],
       [0.92883097, 0.56052232, 0.91243779, 0.623595  ]])

In [88]:
np.random.random((2,3))

array([[0.76720968, 0.11297591, 0.80059827],
       [0.22717098, 0.05256999, 0.17411733]])

In [89]:
np.random.seed(seed=0)
np.random.uniform(1, 3, (4,4))

array([[2.09762701, 2.43037873, 2.20552675, 2.08976637],
       [1.8473096 , 2.29178823, 1.87517442, 2.783546  ],
       [2.92732552, 1.76688304, 2.58345008, 2.05778984],
       [2.13608912, 2.85119328, 1.14207212, 1.1742586 ]])

In [90]:
a = np.array([1,2,3,4,5,6,7,8,9,9])
arr = np.random.choice(a, (2,2))
arr

array([[4, 1],
       [4, 6]])

In [91]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
m_arr = np.random.random(1000000)

%timeit sum(m_arr)  #python method
%timeit np.sum(m_arr) #numpy method

58.6 ms ± 4.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
431 μs ± 48.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
